person:
  firstName: foo
  lastName: bar

person-list:
  personList:
    -
      firstName: baz
      lastName: qux
    -
      firstName: quux
      lastName: corge

bean.person:
  first:
    firstName: grault
    lastName: garply
  second:
    firstName: waldo
    lastName: fred